# Generated by Django 5.0.6 on 2024-06-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
